{{- with .Values.stockwebapi }}
apiVersion: v1
kind: Service
metadata:
  name: stockback-api
spec:
  type: NodePort
  selector:
    app: stockback-api
  ports:
    - port: 8080
      targetPort: {{ .service.portexpose }}
      nodePort: 30080 
{{- end }}
