---
apiVersion: v1
kind: Service
metadata:
  name: stockback-api
spec:
  type: NodePort
  selector:
    app: stockback-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # exposé sur Minikube